baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Quest API"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

disqusShortname = "eqcodex"

[params]
  editURL = "https://github.com/xackery/eqquestapi/edit/master/content/"
  description = "Quest API"
  author = "Shin Noir"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  themeVariant = "eqcodex"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Quest API"
weight = 1
languageName = "English"


[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-info'></i> Beginner's Guide"
url = "/guide"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-discord'></i> Discord"
url = "https://discord.gg/fArqDFE"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/xackery/eqquestapi"
weight = 30


[Languages.fr]
title = "Quest API"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-discord'></i> Discord"
url = "https://discord.gg/nZNvXEm"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 20


[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/eqcodex/eqcodex"
weight = 30

